version: "3"

services:
  db:
    image: postgres:13.6
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
